const SITE_URL = "https://www.roothealth.app";

export default function robots() {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/_next/",
        "/atmospheres/",
        "/personal",
        "/organisations",
        "/privacy",
        "/root-logo.png",
        "/safety",
        "/terms",
        "/visuals/",
      ],
      disallow: [
        "/",
        "/api/",
        "/admin/",
        "/assessment",
        "/body",
        "/choose-experience",
        "/choose-organisation",
        "/coach",
        "/executive-review",
        "/forgot-password",
        "/hr-coach",
        "/insights",
        "/journal",
        "/launch-kit",
        "/login",
        "/mind",
        "/onboarding-complete",
        "/organisation/",
        "/organisation-learning",
        "/organisations/billing",
        "/organisations/checkout",
        "/orientation",
        "/org-insights",
        "/personal/join",
        "/playbook",
        "/presentation-support",
        "/profile",
        "/reconnect",
        "/referral",
        "/reset-password",
        "/root-insight/",
        "/welcome",
        "/workplace",
        "/workplace-applications",
        "/workplace-setup",
      ],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
